{
 "title": "Robot Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Microcontroller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rotation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"position\")"
    }
   ]
  },
  {
   "title": "Distances Front",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"frontLeft\" or r[\"_field\"] == \"frontRight\")"
    }
   ]
  },
  {
   "title": "Distances Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"leftFront\" or r[\"_field\"] == \"leftBack\")"
    }
   ]
  },
  {
   "title": "Distances Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rightFront\" or r[\"_field\"] == \"rightBack\")"
    }
   ]
  },
  {
   "title": "Cerebellum service commands",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"commands\")\n  |> filter(fn: (r) => r[\"service\"] == \"cerebellum\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({ time: r._time, dir: r.direction, val: r._value }))\n  |> sort(columns: [\"time\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "Cerebellum service logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logs\")\n  |> map(fn: (r) => ({ time: r._time, msg_type: r.type, msg: r._value }))\n  |> sort(columns: [\"time\"], desc: true)"
    }
   ]
  },
  { "title": "Character recognition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Prediction - character",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction\")\n  |> filter(fn: (r) => r[\"_field\"] == \"character\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Prediction - chance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction\")\n  |> filter(fn: (r) => r[\"_field\"] == \"chance\")\n  |> map(fn: (r) => ({ _value: r._value }))\n  |> last()"
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 26 },
   "targets": [
    {
     "query": "t1 = from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction\")\n  |> filter(fn: (r) => r[\"_field\"] == \"chance\")\n\nt2 = from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prediction\")\n  |> filter(fn: (r) => r[\"_field\"] == \"character\")\n\njoin(tables: {t1: t1, t2: t2}, on: [\"_time\"])\n|> map(fn: (r) => ({time: r._time, character: r._value_t2, chance: r._value_t1}))\n|> sort(columns: [\"time\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "OCR service commands",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"Sonic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"commands\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"service\"] == \"ocr\")\n  |> map(fn: (r) => ({ time: r._time, dir: r.direction, val: r._value }))\n  |> sort(columns: [\"time\"], desc: true)\n"
    }
   ]
  }
 ]
}